fix compile failures on macos m1
slp/krunvm pull request #1
Opened 2021-01-29 16:45 UTC by dims

```
error[E0425]: cannot find value `rootfs` in this scope
  --> src/start.rs:47:43
   |
47 |         let full_guest = format!("{}{}", &rootfs, guest_path);
   |                                           ^^^^^^ help: a local variable with a similar name exists: `_rootfs`

error[E0133]: call to unsafe function is unsafe and requires unsafe function or block
  --> src/start.rs:61:15
   |
61 |     let ret = bindings::krun_set_mapped_volumes(ctx, vols.as_ptr());
   |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call to unsafe function
   |
   = note: consult the function's documentation for information on how to avoid undefined behavior

```

Signed-off-by: Davanum Srinivas <davanum@gmail.com>

2021-01-29 19:56 UTC, slp requested changes
Thanks for the PR! Looks like I broke the build for macOS with the latest changes for Linux. I hope we'll be able to set up a CI for the first soon.

Apart from a minor issue I've commented above, the change looks good to me.

2021-01-29 19:56 UTC, slp commented on src/start.rs
> +        let ret = bindings::krun_set_mapped_volumes(ctx, vols.as_ptr());
Please restrict the "unsafe" block to the bindings call:

```
let ret = unsafe { bindings::krun_set_mapped_volumes(ctx, vols.as_ptr()) };
```

2021-01-29 19:58 UTC, slp commented
Thanks for reporting this. Looks like the recipe for `buildah` is missing a dependency on `gpgme`. I'm going to transfer this issue to the repository that holds the Homebrew recipes.

2021-01-30 02:00 UTC, dims commented on src/start.rs
> +        let ret = bindings::krun_set_mapped_volumes(ctx, vols.as_ptr());
thanks! done.

2021-01-30 08:30 UTC, slp approved these changes

2021-01-30 08:30 UTC, slp commented
LGTM, thanks a lot!

2021-01-30 08:31 UTC, merged